[project]
name = "daemonhunter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tatinCode", email = "justinbusalpa22@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.20.0",
    "fastapi[standard]>=0.141.1",
    "itsdangerous>=2.2.0",
    "pwdlib[argon2]>=0.3.0",
    "sqlalchemy>=2.0.52",
]

[project.scripts]

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
